### ISSUE TITLE
Action配置

### ISSUE THREAD

**Issue by Damue01** [Lihewin/NUIST_Auto_Health_Report#1]
你好，请问在配置好文件后，Actions里CI有时运行成功，有时失败，报错都是Error: Process completed with exit code 1.
 #而且不按照配置的时间运行，经常会出现不运行的情况
![error](https://user-images.githubusercontent.com/88480659/129009616-78b48084-c790-470f-afb5-8fb5c847a350.png)
[](url)
请问这该怎么解决呢 :C

**Comment by Lihewin** [comment]
actions服务器与学校的连接并不是很稳定，
我有时也碰到这样的问题。
初步估计是脚本中timeout设置不够合理，后面会继续改进。

配置好帐号密码以后如果发生失败，则进入这个workflow重新运行即可。
如果打卡成功，那么会在log中显示成功。
如果问题过多次出现，你也可以部署到自己的电脑或者手机上，这样会更稳定一些。

**Comment by Damue01** [comment]
好的，我之前自己改过几次timeout，但始终找不到合适的值，现在只能让他在早上那段时间多跑几次了。因为github一直挂在梯子上，我倒是把服务器本身的原因给忘记了，感谢
